vrrp_instance VI_APP {
    state <MASTER_OR_BACKUP>
    interface <interface-name>
    virtual_router_id <router-id>
    priority <priority>
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass <shared-secret>
    }

    virtual_ipaddress {
        <vip-cidr>
    }
}
